'use strict';

module.exports = {
    activeSessionId: null,
    sessions: {},
    sessionOrder: [],
    language: 'auto',
    previewNext: true,
    previewPrevious: true,
    confirmDeleteByHotkey: true,
    confirmQuickActions: false,
    autoSaveOnSwitch: true,
    warnOnUnsavedSwitch: true,
    highlightUnsavedSessionChanges: true,
    restoreSidebars: true,
    statusBarQuickSwitcher: true,
    groupFeatureEnabled: true,
    showFilterInput: false,
    overlayDefaultFocus: 'current-session',
    showActiveSwitchCommand: false,
    numberedSwitchCommands: true,
    searchOverlayPosition: null,
    searchOverlaySize: null,
    groups: {},
    groupOrder: [],
    sessionGroups: {},
    activeGroupId: null,
    versionHistoryEnabled: true,
    versionHistorySnapshotInterval: 5,
    versionHistoryCtrlRmbRestore: true,
    versionHistoryConfirmRestore: true,
    statusBarModScrollSwitch: false,
    statusBarScrollPreset: 'trackpad',
    statusBarScrollModifierMode: 'none',
    statusBarScrollThreshold: 30,
    statusBarScrollCooldownMs: 500,
    statusBarScrollResetMs: 250,
    statusBarScrollInvert: false,
    statusBarActions: {
        click:           'quickSwitcher',
        altClick:        'reloadWithoutSaving',
        modClick:        'saveSession',
        shiftClick:      'none',
        middleClick:     'none',
        altMiddleClick:  'none',
        modMiddleClick:  'reloadWithoutSaving',
        shiftMiddleClick:'none',
        rightClick:      'sessionMenu',
        altRightClick:   'none',
        modRightClick:   'restoreLatestHistory',
        shiftRightClick: 'none',
    },
};
