'use strict';

module.exports = {
    activeSessionId: null,
    sessions: {},
    sessionOrder: [],
    language: 'auto',
    previewNext: true,
    previewPrevious: true,
    confirmDeleteByHotkey: true,
    confirmQuickActions: false,
    autoSaveOnSwitch: true,
    warnOnUnsavedSwitch: true,
    statusBarQuickSwitcher: true,
    groupFeatureEnabled: true,
    showFilterInput: false,
    showActiveSwitchCommand: false,
    numberedSwitchCommands: true,
    searchOverlayPosition: null,
    searchOverlaySize: null,
    groups: {},
    groupOrder: [],
    sessionGroups: {},
    activeGroupId: null,
    versionHistoryEnabled: true,
    versionHistorySnapshotInterval: 5,
    versionHistoryCtrlRmbRestore: true,
    versionHistoryConfirmRestore: true,
    statusBarActions: {
        click:           'quickSwitcher',
        altClick:        'reloadWithoutSaving',
        modClick:        'saveSession',
        shiftClick:      'none',
        rightClick:      'sessionMenu',
        altRightClick:   'none',
        modRightClick:   'restoreLatestHistory',
        shiftRightClick: 'none',
    },
};
